name: Code Tests

on: push

jobs:
  testing-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Run tests
        run: |
          pip install .
          pip install -r requirements-dev.txt
          python3 -m pytest .

  testing-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Run tests
        run: |
          pip install .
          pip install -r requirements-dev.txt
          python3 -m pytest .

  testing-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Run tests
        run: |
          pip install .
          pip install -r requirements-dev.txt
          python3 -m pytest . -s
